AWSTemplateFormatVersion: "2010-09-09"
Description: Grafana DNS stack
Parameters:
  #------------------------
  # Deployment Information
  #------------------------
  environment:
    Type: String
    Description: Name of the environment
    Default: production

  #-----------------------
  # Route53 Configuration
  #-----------------------
  Domain:
    Type: String
    Description: The HostedZoneName to create the endpoint on
  SubDomain:
    Type: String
    Description: The subdomain to be used by grafana

  #-----------
  # Resources
  #-----------
  GrafanaDns:
    Type: String
    Description: Load balancer dns endpoint for Grafana

Resources:
  GrafanaEndpoint:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub "${Domain}."
      Comment: 'DNS name for nakama'
      Name: !Sub "${SubDomain}.${Domain}."
      Type: CNAME
      TTL: '300'
      ResourceRecords:
        - !Ref GrafanaDns

Outputs:
  GrafanaEndpoint:
    Description: 'DNS name for Grafana'
    Value: !Sub "${SubDomain}.${Domain}."