AWSTemplateFormatVersion: '2010-09-09'
Description: Grafana ECS Task
Parameters:
  LogGroupName:
    Type: String
    Description: The AWS CloudWatch log group to output logs to.
    Default: "/ecs/grafana"

Resources:


  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
      LogGroupName: !Ref LogGroupName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      - Name: grafana
        Essential: 'true'
        Image: "grafana/grafana:6.7.3"
        MemoryReservation: 800
        PortMappings:
        - HostPort: 0
          ContainerPort: 3000
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-region:
              Ref: AWS::Region
            awslogs-group:
              Ref: LogGroup
Outputs:
  TaskArn:
    Description: ARN of the TaskDefinition
    Value: !Ref TaskDefinition